os:
- linux
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
- python setup.py install
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: danwos
  password:
    secure: orttbEJYmZmDH2fbis81MPPgaxni4O7BpyzkiY8m1e6J0ilUxOQzG4z3NCylEgU2G2RWMz0368mJ0Ywettl8qisznHj3Qbg3BB7mULVE/RJFr6+JFtms5b8d0M/gpyymOGtuKIDEXTHFU7WvTOcATueuewbUygq+mmJh83d6R6a/ogrJvm1t41ykJbAe7vAouSjfcES5kdsNB2BBvsXSx8UniU/N/eVOxwHVLS81uJ226JBdP9/aibTUc56HHUkLtZBaRn1dZEZl7Ji6zCYLTOo9bzcAR5hvrj/dkVCPWq5nCbiYrb5XDmafGaVAWE9vDVhDlxrpnW1sNIfUuRHvkB4eRTrWo6P6+loVlWHhxxZu/nIhD5u1wFxhrBSrMJ1spoqj7lu95NARWkNSR98xByEghfKE3werHlzq1fe2jRiPzg9OUretxEl0MxluvzsjyMDHk8ve6V3qbFwSkpKrm8kS7SNouVWq3mSGkqMQe9eESyD0z8SMCh1hxzguGiOFAM8KA2HVMPiiX6RhRKaAX2+8Y/hgGJBYDWqSV+NuDKuEo99PSoi+twpDLqtNhgI4Yv13hk4N3Uujmel7s22kxKe43/JTzbG6sHACILz6i7Me9JN+oScPBqC/nZL6skiqgnV4kD7U/LAZYiCchw3y8K4byNlBvY09EX/c6hd8cuU=
  on:
    tags: true
    branch: master
